Update Build and Release.yml

diff --git a/.github/workflows/Build and Release.yml b/.github/workflows/Build and Release.yml
--- a/.github/workflows/Build and Release.yml
+++ b/.github/workflows/Build and Release.yml
@@ -1002,3 +1002,17 @@ jobs:
       run: |
         ls -R Build_Components || echo "no folder"
         find . -name "*.ipa" || echo "no ipa"
+
+    - name: Debug IPA output
+      run: |
+        echo "=== Build_Components ==="
+        ls -R Build_Components || echo "Folder missing"
+
+        echo "=== Search IPA ==="
+        find . -name "*.ipa" || echo "No IPA found"
+
+    - name: Upload IPA
+      uses: actions/upload-artifact@v4
+      with:
+        name: ipa
+        path: Build_Components/*.ipa
